fix(utils): run git clone in separate tmux window

diff --git a/utils/.local/bin/git-clone-tmux b/utils/.local/bin/git-clone-tmux
--- a/utils/.local/bin/git-clone-tmux
+++ b/utils/.local/bin/git-clone-tmux
@@ -3,32 +3,28 @@
 set -eou pipefail
 
 # Clone a git repo and open it in a new tmux window
-# Requires: gh, glab, git
-REPO_URL="${1:-$(gum input --placeholder="GitHub Repo URL" --width=80)}"
+# Requires: gh, glab, git, fzf
+REPO_URL="${1:-}"
 CLONE_PATH=""
 
 if [[ -z "${REPO_URL}" ]]; then
-	echo "ERROR: missing REPO_URL"
-	exit 1
+  exit 1
 fi
 
 if [[ "${REPO_URL}" =~ ^https://github ]]; then
-	GITHUB_ORG_REPO="$(echo "${REPO_URL%.git}" | cut -d '/' -f 3-5)"
-	CLONE_PATH="${HOME}/Projects/${GITHUB_ORG_REPO}"
-	mkdir -p "${CLONE_PATH}"
-	git clone "${REPO_URL}" "${CLONE_PATH}"
+  GITHUB_ORG_REPO="$(echo "${REPO_URL%.git}" | cut -d '/' -f 3-5)"
+  CLONE_PATH="${HOME}/Projects/${GITHUB_ORG_REPO}"
+  mkdir -p "${CLONE_PATH}"
 elif [[ "${REPO_URL}" =~ ^https://gitlab ]]; then
-	GITLAB_GROUP_REPO="$(echo "${REPO_URL%.git}" | cut -d '/' -f 3-)"
-	CLONE_PATH="${HOME}/Projects/${GITLAB_GROUP_REPO}"
-	mkdir -p "${CLONE_PATH}"
-	git clone "${REPO_URL}" "${CLONE_PATH}"
+  GITLAB_GROUP_REPO="$(echo "${REPO_URL%.git}" | cut -d '/' -f 3-)"
+  CLONE_PATH="${HOME}/Projects/${GITLAB_GROUP_REPO}"
+  mkdir -p "${CLONE_PATH}"
 elif [[ "${REPO_URL}" =~ ^https://bitbucket ]]; then
-	BITBUCKET_WORKSPACE="$(echo "${REPO_URL%/src*}" | cut -d '/' -f 3-5)"
-	CLONE_PATH="${HOME}/Projects/${BITBUCKET_WORKSPACE}"
-	mkdir -p "${CLONE_PATH}"
-	git clone "${REPO_URL}" "${CLONE_PATH}"
+  BITBUCKET_WORKSPACE="$(echo "${REPO_URL%/src*}" | cut -d '/' -f 3-5)"
+  CLONE_PATH="${HOME}/Projects/${BITBUCKET_WORKSPACE}"
+  mkdir -p "${CLONE_PATH}"
 else
-	echo "ERROR: Unknown Git hosting platform."
+  echo "ERROR: Unknown Git hosting platform."
 fi
 
-tmux new-window -c "${CLONE_PATH}" -n "$(basename "${CLONE_PATH}")"
+tmux split-window "git clone ${REPO_URL} ${CLONE_PATH} && tmux new-window -c ${CLONE_PATH}"
